import { Role, User } from '@domain/entities'
import { RolesEnum, UserStatusEnum } from '@domain/enums'
import { MigrationInterface, QueryRunner } from 'typeorm'

const residentsSeed = [
  {
    name: 'Vernice Hagwood',
    email: 'vhagwood0@auda.org.au',
    password: 'liberaai2023',
    cpf: '41983979619',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: "Denver O'Halloran",
    email: 'dohalloran1@exblog.jp',
    password: 'liberaai2023',
    cpf: '36432109736',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Murdoch Radloff',
    email: 'mradloff2@linkedin.com',
    password: 'liberaai2023',
    cpf: '60663083516',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Lin Holde',
    email: 'lholde3@techcrunch.com',
    password: 'liberaai2023',
    cpf: '16724295521',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Malia Limrick',
    email: 'mlimrick4@wunderground.com',
    password: 'liberaai2023',
    cpf: '40853792917',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kissie Bertome',
    email: 'kbertome5@sfgate.com',
    password: 'liberaai2023',
    cpf: '50599106794',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Petrina Norgan',
    email: 'pnorgan6@nymag.com',
    password: 'liberaai2023',
    cpf: '35894008468',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Jedediah Trice',
    email: 'jtrice7@omniture.com',
    password: 'liberaai2023',
    cpf: '62802992015',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Devan Gyer',
    email: 'dgyer8@china.com.cn',
    password: 'liberaai2023',
    cpf: '04407870095',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Ferguson Grayson',
    email: 'fgrayson9@amazon.co.jp',
    password: 'liberaai2023',
    cpf: '55624005024',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Ebenezer Ilsley',
    email: 'eilsleya@craigslist.org',
    password: 'liberaai2023',
    cpf: '25786886565',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Fernandina Bartoleyn',
    email: 'fbartoleynb@xinhuanet.com',
    password: 'liberaai2023',
    cpf: '79082719100',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kaylil Niset',
    email: 'knisetc@yolasite.com',
    password: 'liberaai2023',
    cpf: '19705459177',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Felecia Nelsey',
    email: 'fnelseyd@google.cn',
    password: 'liberaai2023',
    cpf: '15477663103',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Gram Penelli',
    email: 'gpenellie@multiply.com',
    password: 'liberaai2023',
    cpf: '32209750385',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Townie Godlonton',
    email: 'tgodlontonf@yahoo.co.jp',
    password: 'liberaai2023',
    cpf: '02547694972',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Jessie Kurth',
    email: 'jkurthg@ed.gov',
    password: 'liberaai2023',
    cpf: '25445807550',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Esteban Mathes',
    email: 'emathesh@posterous.com',
    password: 'liberaai2023',
    cpf: '01292228105',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Urban Pallasch',
    email: 'upallaschi@homestead.com',
    password: 'liberaai2023',
    cpf: '68178559188',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Gannie Brind',
    email: 'gbrindj@oaic.gov.au',
    password: 'liberaai2023',
    cpf: '32124872320',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Immanuel Pfeuffer',
    email: 'ipfeufferk@purevolume.com',
    password: 'liberaai2023',
    cpf: '26212965641',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kristy Tchaikovsky',
    email: 'ktchaikovskyl@discovery.com',
    password: 'liberaai2023',
    cpf: '41407937324',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Darcie Wandrack',
    email: 'dwandrackm@shareasale.com',
    password: 'liberaai2023',
    cpf: '79103346994',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Philis Dineen',
    email: 'pdineenn@yandex.ru',
    password: 'liberaai2023',
    cpf: '87001568171',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Fredelia Ledwith',
    email: 'fledwitho@usgs.gov',
    password: 'liberaai2023',
    cpf: '90334736587',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Liesa Barz',
    email: 'lbarzp@constantcontact.com',
    password: 'liberaai2023',
    cpf: '01185701532',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Sissy Scinelli',
    email: 'sscinelliq@1und1.de',
    password: 'liberaai2023',
    cpf: '20640797857',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Nefen McGiveen',
    email: 'nmcgiveenr@canalblog.com',
    password: 'liberaai2023',
    cpf: '81590886046',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Erskine Caves',
    email: 'ecavess@blogs.com',
    password: 'liberaai2023',
    cpf: '34844518313',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Darla Felgat',
    email: 'dfelgatt@livejournal.com',
    password: 'liberaai2023',
    cpf: '37353780568',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Gabbie Hexam',
    email: 'ghexamu@apple.com',
    password: 'liberaai2023',
    cpf: '21329016351',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Shanon Dobbins',
    email: 'sdobbinsv@t.co',
    password: 'liberaai2023',
    cpf: '73903214078',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Peyton Castagnone',
    email: 'pcastagnonew@bbc.co.uk',
    password: 'liberaai2023',
    cpf: '32860540466',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Wallie Ben',
    email: 'wbenx@businessinsider.com',
    password: 'liberaai2023',
    cpf: '54582113915',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Keefe Gutherson',
    email: 'kguthersony@multiply.com',
    password: 'liberaai2023',
    cpf: '59757146994',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Jan Deshorts',
    email: 'jdeshortsz@netvibes.com',
    password: 'liberaai2023',
    cpf: '68773901806',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Felisha Banaszkiewicz',
    email: 'fbanaszkiewicz10@hostgator.com',
    password: 'liberaai2023',
    cpf: '28438610633',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: "Emile O'Crowley",
    email: 'eocrowley11@psu.edu',
    password: 'liberaai2023',
    cpf: '16875971461',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Meagan Smidmoor',
    email: 'msmidmoor12@businessweek.com',
    password: 'liberaai2023',
    cpf: '13263317873',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Arleta Galey',
    email: 'agaley13@google.com.br',
    password: 'liberaai2023',
    cpf: '84613437601',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Christian Shrieve',
    email: 'cshrieve14@fotki.com',
    password: 'liberaai2023',
    cpf: '11424727952',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Windy Boddington',
    email: 'wboddington15@symantec.com',
    password: 'liberaai2023',
    cpf: '54133646959',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Ozzie Grzesiak',
    email: 'ogrzesiak16@networksolutions.com',
    password: 'liberaai2023',
    cpf: '67581459217',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Rosaleen Scrivin',
    email: 'rscrivin17@ifeng.com',
    password: 'liberaai2023',
    cpf: '91602639469',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Dorris Dacre',
    email: 'ddacre18@edublogs.org',
    password: 'liberaai2023',
    cpf: '96068594602',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Felice Dewar',
    email: 'fdewar19@sun.com',
    password: 'liberaai2023',
    cpf: '53140411383',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Leonie Atchly',
    email: 'latchly1a@about.com',
    password: 'liberaai2023',
    cpf: '19097243009',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Hector Kendall',
    email: 'hkendall1b@odnoklassniki.ru',
    password: 'liberaai2023',
    cpf: '01072964546',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Lacee Martyntsev',
    email: 'lmartyntsev1c@dion.ne.jp',
    password: 'liberaai2023',
    cpf: '82941715657',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Jackson Noteyoung',
    email: 'jnoteyoung1d@sphinn.com',
    password: 'liberaai2023',
    cpf: '47140181675',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Franny Pidgin',
    email: 'fpidgin1e@ox.ac.uk',
    password: 'liberaai2023',
    cpf: '79751192102',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Mickey Screech',
    email: 'mscreech1f@lycos.com',
    password: 'liberaai2023',
    cpf: '14293664009',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Michaelina Alldridge',
    email: 'malldridge1g@discovery.com',
    password: 'liberaai2023',
    cpf: '37435365106',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Cynthy Worsnup',
    email: 'cworsnup1h@pinterest.com',
    password: 'liberaai2023',
    cpf: '48876294945',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Bartie Bobasch',
    email: 'bbobasch1i@mediafire.com',
    password: 'liberaai2023',
    cpf: '74790566056',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Aline Ramble',
    email: 'aramble1j@feedburner.com',
    password: 'liberaai2023',
    cpf: '39826859400',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Marlie Cranefield',
    email: 'mcranefield1k@disqus.com',
    password: 'liberaai2023',
    cpf: '59357560483',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Reed McPhelim',
    email: 'rmcphelim1l@spiegel.de',
    password: 'liberaai2023',
    cpf: '18542866410',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Jacobo Cossam',
    email: 'jcossam1m@sitemeter.com',
    password: 'liberaai2023',
    cpf: '23605055133',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Bradford McMenamy',
    email: 'bmcmenamy1n@time.com',
    password: 'liberaai2023',
    cpf: '77988789716',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Den Bronot',
    email: 'dbronot1o@amazon.de',
    password: 'liberaai2023',
    cpf: '95576001958',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Andie Anfrey',
    email: 'aanfrey1p@paginegialle.it',
    password: 'liberaai2023',
    cpf: '55141211274',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Terri Nulty',
    email: 'tnulty1q@discuz.net',
    password: 'liberaai2023',
    cpf: '12945391163',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Robina Harral',
    email: 'rharral1r@mail.ru',
    password: 'liberaai2023',
    cpf: '25244169688',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Jeffie Seymark',
    email: 'jseymark1s@ihg.com',
    password: 'liberaai2023',
    cpf: '78766609593',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Lissa Danjoie',
    email: 'ldanjoie1t@about.com',
    password: 'liberaai2023',
    cpf: '52311401718',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Milly Phillot',
    email: 'mphillot1u@eepurl.com',
    password: 'liberaai2023',
    cpf: '12601067560',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Alain Waters',
    email: 'awaters1v@squarespace.com',
    password: 'liberaai2023',
    cpf: '99274375875',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Merrilee Pearne',
    email: 'mpearne1w@tiny.cc',
    password: 'liberaai2023',
    cpf: '86017288202',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Valenka Shotbolt',
    email: 'vshotbolt1x@youtube.com',
    password: 'liberaai2023',
    cpf: '44959879254',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Farr Risely',
    email: 'frisely1y@cloudflare.com',
    password: 'liberaai2023',
    cpf: '80717291324',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Moyra Benham',
    email: 'mbenham1z@amazon.com',
    password: 'liberaai2023',
    cpf: '29199700549',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Emily Rollett',
    email: 'erollett20@dot.gov',
    password: 'liberaai2023',
    cpf: '65569309977',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Martica Matura',
    email: 'mmatura21@rediff.com',
    password: 'liberaai2023',
    cpf: '15333914400',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Juliet Winsper',
    email: 'jwinsper22@shinystat.com',
    password: 'liberaai2023',
    cpf: '07097541407',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Jacinta Ragsdale',
    email: 'jragsdale23@omniture.com',
    password: 'liberaai2023',
    cpf: '36000497555',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Paolo Schleicher',
    email: 'pschleicher24@blogs.com',
    password: 'liberaai2023',
    cpf: '91236803507',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Torrin Cotterel',
    email: 'tcotterel25@1und1.de',
    password: 'liberaai2023',
    cpf: '13753455326',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Noble Jagielski',
    email: 'njagielski26@cocolog-nifty.com',
    password: 'liberaai2023',
    cpf: '45579536623',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Mickie Folliss',
    email: 'mfolliss27@issuu.com',
    password: 'liberaai2023',
    cpf: '60748920161',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Seana Crowdace',
    email: 'scrowdace28@usnews.com',
    password: 'liberaai2023',
    cpf: '74073700529',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Arline Pledge',
    email: 'apledge29@independent.co.uk',
    password: 'liberaai2023',
    cpf: '40518357589',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Ramona Aseef',
    email: 'raseef2a@cornell.edu',
    password: 'liberaai2023',
    cpf: '69734994301',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Reinaldo Nemchinov',
    email: 'rnemchinov2b@liveinternet.ru',
    password: 'liberaai2023',
    cpf: '10220624097',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Ignatius Saul',
    email: 'isaul2c@walmart.com',
    password: 'liberaai2023',
    cpf: '70324596685',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Konstance Belitz',
    email: 'kbelitz2d@businessweek.com',
    password: 'liberaai2023',
    cpf: '71864194707',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Chickie Benedit',
    email: 'cbenedit2e@sogou.com',
    password: 'liberaai2023',
    cpf: '87716492802',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Marie Giacobelli',
    email: 'mgiacobelli2f@addtoany.com',
    password: 'liberaai2023',
    cpf: '68682168316',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Dulci Dallimore',
    email: 'ddallimore2g@clickbank.net',
    password: 'liberaai2023',
    cpf: '40648675998',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Hubie Forster',
    email: 'hforster2h@cbsnews.com',
    password: 'liberaai2023',
    cpf: '70201934639',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Susanne Matyasik',
    email: 'smatyasik2i@huffingtonpost.com',
    password: 'liberaai2023',
    cpf: '73902810220',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Edsel Cubin',
    email: 'ecubin2j@nps.gov',
    password: 'liberaai2023',
    cpf: '74676483678',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Michal Sorsby',
    email: 'msorsby2k@typepad.com',
    password: 'liberaai2023',
    cpf: '78222987399',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Stoddard Hartigan',
    email: 'shartigan2l@theatlantic.com',
    password: 'liberaai2023',
    cpf: '46765261133',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Shelbi Ramalho',
    email: 'sramalho2m@mapquest.com',
    password: 'liberaai2023',
    cpf: '97195670317',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Bennett Garbutt',
    email: 'bgarbutt2n@jugem.jp',
    password: 'liberaai2023',
    cpf: '83480143652',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Obadiah Valentino',
    email: 'ovalentino2o@sun.com',
    password: 'liberaai2023',
    cpf: '79050520103',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Mair Nellen',
    email: 'mnellen2p@ucla.edu',
    password: 'liberaai2023',
    cpf: '69299099472',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Darb Children',
    email: 'dchildren2q@sfgate.com',
    password: 'liberaai2023',
    cpf: '76788653259',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Hedi Hourican',
    email: 'hhourican2r@t-online.de',
    password: 'liberaai2023',
    cpf: '32067721178',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kettie Pagel',
    email: 'kpagel2s@wikimedia.org',
    password: 'liberaai2023',
    cpf: '93639849400',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Silvana Leynagh',
    email: 'sleynagh2t@admin.ch',
    password: 'liberaai2023',
    cpf: '32245164105',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Barty Wallen',
    email: 'bwallen2u@msn.com',
    password: 'liberaai2023',
    cpf: '79574696553',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Royal Ruddiforth',
    email: 'rruddiforth2v@com.com',
    password: 'liberaai2023',
    cpf: '25748247259',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Maggi Scurfield',
    email: 'mscurfield2w@yahoo.com',
    password: 'liberaai2023',
    cpf: '56243409660',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Bradly Antonognoli',
    email: 'bantonognoli2x@ucsd.edu',
    password: 'liberaai2023',
    cpf: '31024311279',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Essy Sketch',
    email: 'esketch2y@amazon.co.uk',
    password: 'liberaai2023',
    cpf: '38299757088',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Fifi Stables',
    email: 'fstables2z@vk.com',
    password: 'liberaai2023',
    cpf: '57374663102',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Dilly McKie',
    email: 'dmckie30@51.la',
    password: 'liberaai2023',
    cpf: '96853383370',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Guenevere Aires',
    email: 'gaires31@google.fr',
    password: 'liberaai2023',
    cpf: '80946047278',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Deloria Spawell',
    email: 'dspawell32@gmpg.org',
    password: 'liberaai2023',
    cpf: '08026374428',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'June Greensite',
    email: 'jgreensite33@hatena.ne.jp',
    password: 'liberaai2023',
    cpf: '65826453664',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kial Robberts',
    email: 'krobberts34@slideshare.net',
    password: 'liberaai2023',
    cpf: '33692765266',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Clarey Packham',
    email: 'cpackham35@bravesites.com',
    password: 'liberaai2023',
    cpf: '29753204850',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Briant Sebrens',
    email: 'bsebrens36@uiuc.edu',
    password: 'liberaai2023',
    cpf: '35712934876',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Faulkner Leverette',
    email: 'fleverette37@icq.com',
    password: 'liberaai2023',
    cpf: '99595495425',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Crichton Turnbull',
    email: 'cturnbull38@dion.ne.jp',
    password: 'liberaai2023',
    cpf: '26307695005',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kellina Bode',
    email: 'kbode39@dailymail.co.uk',
    password: 'liberaai2023',
    cpf: '81561399337',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Riki Harber',
    email: 'rharber3a@vinaora.com',
    password: 'liberaai2023',
    cpf: '85869023653',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Amandi Briton',
    email: 'abriton3b@ibm.com',
    password: 'liberaai2023',
    cpf: '24238480996',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Cassaundra Surplice',
    email: 'csurplice3c@addthis.com',
    password: 'liberaai2023',
    cpf: '37693155457',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Olympie Endrizzi',
    email: 'oendrizzi3d@aol.com',
    password: 'liberaai2023',
    cpf: '31581716940',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Albie Keasy',
    email: 'akeasy3e@godaddy.com',
    password: 'liberaai2023',
    cpf: '11200765796',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Jeannine Eldrid',
    email: 'jeldrid3f@a8.net',
    password: 'liberaai2023',
    cpf: '23446790900',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Hunter Hardbattle',
    email: 'hhardbattle3g@4shared.com',
    password: 'liberaai2023',
    cpf: '91356626700',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Rycca Hanvey',
    email: 'rhanvey3h@reverbnation.com',
    password: 'liberaai2023',
    cpf: '23564834117',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Fidela Peniman',
    email: 'fpeniman3i@cdc.gov',
    password: 'liberaai2023',
    cpf: '54501938153',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Brunhilde Conrart',
    email: 'bconrart3j@multiply.com',
    password: 'liberaai2023',
    cpf: '87399370389',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: "Antonio O'Kelly",
    email: 'aokelly3k@home.pl',
    password: 'liberaai2023',
    cpf: '93804322409',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Lu Stidson',
    email: 'lstidson3l@google.pl',
    password: 'liberaai2023',
    cpf: '01136441832',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kessiah MacClay',
    email: 'kmacclay3m@arizona.edu',
    password: 'liberaai2023',
    cpf: '17953434199',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Lona Zanioletti',
    email: 'lzanioletti3n@comsenz.com',
    password: 'liberaai2023',
    cpf: '57488201612',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Carny Poundesford',
    email: 'cpoundesford3o@dell.com',
    password: 'liberaai2023',
    cpf: '81865895709',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Rhett Hassell',
    email: 'rhassell3p@altervista.org',
    password: 'liberaai2023',
    cpf: '36262322981',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Maighdiln Tantum',
    email: 'mtantum3q@oracle.com',
    password: 'liberaai2023',
    cpf: '48787910470',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Klemens Crich',
    email: 'kcrich3r@hatena.ne.jp',
    password: 'liberaai2023',
    cpf: '59560007831',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kym Preble',
    email: 'kpreble3s@marriott.com',
    password: 'liberaai2023',
    cpf: '43878825730',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Clair Sedman',
    email: 'csedman3t@facebook.com',
    password: 'liberaai2023',
    cpf: '34409084704',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Agretha Venediktov',
    email: 'avenediktov3u@altervista.org',
    password: 'liberaai2023',
    cpf: '82984651219',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: "Ivory O'Nion",
    email: 'ionion3v@indiatimes.com',
    password: 'liberaai2023',
    cpf: '42724954025',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Ofilia Mustarde',
    email: 'omustarde3w@skype.com',
    password: 'liberaai2023',
    cpf: '68778048214',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Claudetta Housen',
    email: 'chousen3x@themeforest.net',
    password: 'liberaai2023',
    cpf: '18670382423',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Nicolais Hargreves',
    email: 'nhargreves3y@blogspot.com',
    password: 'liberaai2023',
    cpf: '69666728907',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Radcliffe Downing',
    email: 'rdowning3z@weibo.com',
    password: 'liberaai2023',
    cpf: '64856217682',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Lyn Sorrel',
    email: 'lsorrel40@netvibes.com',
    password: 'liberaai2023',
    cpf: '63754392727',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kirk Waywell',
    email: 'kwaywell41@businessinsider.com',
    password: 'liberaai2023',
    cpf: '82287151613',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Arvy Joll',
    email: 'ajoll42@nifty.com',
    password: 'liberaai2023',
    cpf: '11944884718',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Brynne Reagan',
    email: 'breagan43@bravesites.com',
    password: 'liberaai2023',
    cpf: '47980837550',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Faunie Matchell',
    email: 'fmatchell44@spiegel.de',
    password: 'liberaai2023',
    cpf: '66241852523',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Mill Marioneau',
    email: 'mmarioneau45@nifty.com',
    password: 'liberaai2023',
    cpf: '57698381676',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Buddie Lushey',
    email: 'blushey46@xing.com',
    password: 'liberaai2023',
    cpf: '30305522175',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Inglebert Tuttle',
    email: 'ituttle47@technorati.com',
    password: 'liberaai2023',
    cpf: '81880357500',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Dacia Hayley',
    email: 'dhayley48@simplemachines.org',
    password: 'liberaai2023',
    cpf: '35634010209',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Tanhya Poacher',
    email: 'tpoacher49@cam.ac.uk',
    password: 'liberaai2023',
    cpf: '29838767727',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Margery Madre',
    email: 'mmadre4a@lulu.com',
    password: 'liberaai2023',
    cpf: '08608472414',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Ladonna Ausello',
    email: 'lausello4b@cloudflare.com',
    password: 'liberaai2023',
    cpf: '90206622368',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Homere Rydings',
    email: 'hrydings4c@princeton.edu',
    password: 'liberaai2023',
    cpf: '21147550700',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Hazlett Viollet',
    email: 'hviollet4d@statcounter.com',
    password: 'liberaai2023',
    cpf: '37225357603',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Paddie Band',
    email: 'pband4e@desdev.cn',
    password: 'liberaai2023',
    cpf: '05597483889',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Arlinda Cruikshank',
    email: 'acruikshank4f@gov.uk',
    password: 'liberaai2023',
    cpf: '94854918160',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Fraser Thorneywork',
    email: 'fthorneywork4g@msn.com',
    password: 'liberaai2023',
    cpf: '85036377079',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'John Pottell',
    email: 'jpottell4h@jugem.jp',
    password: 'liberaai2023',
    cpf: '76076798475',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kylila Flancinbaum',
    email: 'kflancinbaum4i@unesco.org',
    password: 'liberaai2023',
    cpf: '25142568605',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Elset Coleiro',
    email: 'ecoleiro4j@scribd.com',
    password: 'liberaai2023',
    cpf: '54814724144',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Lynnett Merlin',
    email: 'lmerlin4k@xing.com',
    password: 'liberaai2023',
    cpf: '54519048710',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Troy MacEnelly',
    email: 'tmacenelly4l@drupal.org',
    password: 'liberaai2023',
    cpf: '73024098038',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Danielle Gellett',
    email: 'dgellett4m@nytimes.com',
    password: 'liberaai2023',
    cpf: '06104969992',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Adella Ruckert',
    email: 'aruckert4n@gmpg.org',
    password: 'liberaai2023',
    cpf: '64185804512',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Sam Frampton',
    email: 'sframpton4o@de.vu',
    password: 'liberaai2023',
    cpf: '63184799700',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Zondra Tribell',
    email: 'ztribell4p@upenn.edu',
    password: 'liberaai2023',
    cpf: '55253850589',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Anni Helleker',
    email: 'ahelleker4q@photobucket.com',
    password: 'liberaai2023',
    cpf: '04470417386',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Terrell Birrel',
    email: 'tbirrel4r@nature.com',
    password: 'liberaai2023',
    cpf: '82338431057',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Anabella MacVicar',
    email: 'amacvicar4s@tinypic.com',
    password: 'liberaai2023',
    cpf: '72446862772',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Delila Eberts',
    email: 'deberts4t@chron.com',
    password: 'liberaai2023',
    cpf: '30420860975',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Itch Kield',
    email: 'ikield4u@amazon.co.jp',
    password: 'liberaai2023',
    cpf: '86705506016',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Ealasaid Peggs',
    email: 'epeggs4v@taobao.com',
    password: 'liberaai2023',
    cpf: '25201076696',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Paulie Greatex',
    email: 'pgreatex4w@github.com',
    password: 'liberaai2023',
    cpf: '55127182319',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Abel Nottingam',
    email: 'anottingam4x@topsy.com',
    password: 'liberaai2023',
    cpf: '89378987052',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Madalyn Dooler',
    email: 'mdooler4y@oakley.com',
    password: 'liberaai2023',
    cpf: '47360104017',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Ainsley Barenskie',
    email: 'abarenskie4z@vinaora.com',
    password: 'liberaai2023',
    cpf: '41107255260',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Nev Wormstone',
    email: 'nwormstone50@nhs.uk',
    password: 'liberaai2023',
    cpf: '97744942370',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Hayes Picken',
    email: 'hpicken51@infoseek.co.jp',
    password: 'liberaai2023',
    cpf: '59372160598',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Cassandre Gamage',
    email: 'cgamage52@macromedia.com',
    password: 'liberaai2023',
    cpf: '86187725425',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Suzann Ciric',
    email: 'sciric53@dailymail.co.uk',
    password: 'liberaai2023',
    cpf: '48776645991',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Mechelle Tewelson',
    email: 'mtewelson54@wsj.com',
    password: 'liberaai2023',
    cpf: '63056202701',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Richmound Hurcombe',
    email: 'rhurcombe55@shinystat.com',
    password: 'liberaai2023',
    cpf: '82029746231',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Cymbre Northcliffe',
    email: 'cnorthcliffe56@gnu.org',
    password: 'liberaai2023',
    cpf: '32400797471',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Jeff Churchouse',
    email: 'jchurchouse57@unesco.org',
    password: 'liberaai2023',
    cpf: '97719200730',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Engracia Dingwall',
    email: 'edingwall58@typepad.com',
    password: 'liberaai2023',
    cpf: '88529748573',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Paulita Brunnstein',
    email: 'pbrunnstein59@illinois.edu',
    password: 'liberaai2023',
    cpf: '61692227602',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Hollis Verzey',
    email: 'hverzey5a@gov.uk',
    password: 'liberaai2023',
    cpf: '79679288226',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Karie Isakowicz',
    email: 'kisakowicz5b@ask.com',
    password: 'liberaai2023',
    cpf: '04005988504',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Adi Husset',
    email: 'ahusset5c@flavors.me',
    password: 'liberaai2023',
    cpf: '00219895244',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Kora Dammarell',
    email: 'kdammarell5d@friendfeed.com',
    password: 'liberaai2023',
    cpf: '41105208788',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Ranice Giacoppoli',
    email: 'rgiacoppoli5e@rakuten.co.jp',
    password: 'liberaai2023',
    cpf: '98590584313',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Flo Opie',
    email: 'fopie5f@fema.gov',
    password: 'liberaai2023',
    cpf: '92573540596',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Chicky Scollard',
    email: 'cscollard5g@instagram.com',
    password: 'liberaai2023',
    cpf: '68646904075',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Nikolai Eastbrook',
    email: 'neastbrook5h@telegraph.co.uk',
    password: 'liberaai2023',
    cpf: '60165715472',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Rasia Bartolomeotti',
    email: 'rbartolomeotti5i@usda.gov',
    password: 'liberaai2023',
    cpf: '57493328706',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
  {
    name: 'Victor Gillmor',
    email: 'vgillmor5j@oracle.com',
    password: 'liberaai2023',
    cpf: '33703662239',
    birthdate: new Date(),
    status: UserStatusEnum.INACTIVE,
  },
]

export class SeedResidents1694560638638 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const residentRole = await queryRunner.manager
      .getRepository(Role)
      .findOne({ where: { name: RolesEnum.RESIDENT } })

    const residents = residentsSeed.map((resident) =>
      queryRunner.manager.getRepository(User).create({
        ...resident,
        roles: [residentRole],
      }),
    )

    await queryRunner.manager.getRepository(User).save(residents)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const createdCpfs = residentsSeed.map((resident) => resident.cpf)

    await queryRunner.manager
      .getRepository(User)
      .createQueryBuilder()
      .where('cpf IN (:cpfs)', {
        cpfs: createdCpfs,
      })
      .delete()
      .execute()
  }
}
