version: '3.7'

services:
  api:
    container_name: test_licitar_api
    build:
      context: .
      target: development
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # - redis
  # redis:
  #   container_name: test_licitar_redis
  #   image: redis
  #   command: redis-server --requirepass redis
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - backend
  database:
    container_name: test_licitar_db
    image: postgres:15-alpine

    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - backend
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data:
